version: '3.5'
services:
  server:
    volumes:
      - .:/app
    command: sh -c 'yarn --production=false && yarn clean && yarn build-app && yarn serve --project "$FB_PROJECTID"'
    environment:
      NODE_ENV: '${NODE_ENV}'
      GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_APPLICATION_CREDENTIALS}'
      FIREBASE_TOKEN: '${FIREBASE_TOKEN}'
    ports:
      - '3000:3000'
      - '5000:5000'
