/**
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// [START ai_logic_sensitive_data_all]
// [START ai_logic_pre_request]
// [START ai_logic_imports]
import { logger } from "firebase-functions";
import {
  beforeGenerateContent,
  afterGenerateContent,
} from "firebase-functions/v2/ai";
import { DlpServiceClient } from "@google-cloud/dlp";
// [END ai_logic_imports]

// [START ai_logic_redact_helper]
let dlp = new DlpServiceClient();

/**
 * Redacts sensitive data from a text string using Cloud Sensitive Data Protection (DLP).
 *
 * Inspects for basic sensitive infoTypes (email, phone number, credit card number, SSN)
 * and replaces detected values with their infoType placeholder (e.g. "[EMAIL_ADDRESS]").
 *
 * @param {string} text - The raw input text string to inspect and redact.
 * @returns {Promise<string>} The redacted text, or the original text if empty or unchanged.
 */
export async function redactSensitiveData(text) {
  if (typeof text !== "string" || !text.trim()) {
    return text;
  }

  const projectId = await dlp.getProjectId();

  const [response] = await dlp.deidentifyContent({
    parent: `projects/${projectId}/locations/global`,
    item: { value: text },
    inspectConfig: {
      infoTypes: [
        { name: "EMAIL_ADDRESS" },
        { name: "PHONE_NUMBER" },
        { name: "CREDIT_CARD_NUMBER" },
        { name: "US_SOCIAL_SECURITY_NUMBER" },
      ],
    },
    deidentifyConfig: {
      infoTypeTransformations: {
        transformations: [
          {
            primitiveTransformation: {
              replaceWithInfoTypeConfig: {},
            },
          },
        ],
      },
    },
  });

  return response?.item?.value ?? text;
}
// [END ai_logic_redact_helper]

// [START ai_logic_before_generate_content]
/**
 * Pre-request trigger for Firebase AI Logic.
 * Runs before each generateContent request is forwarded to the Gemini API.
 * Intercepts the request and redacts sensitive data (PII) from prompt contents
 * and system instructions before reaching the model.
 */
export const redactPrompt = beforeGenerateContent(async (event) => {
  const request = event.data?.request;
  if (!request) return;

  let modified = false;

  // Redact sensitive data from prompt contents
  for (const content of request.contents ?? []) {
    for (const part of content?.parts ?? []) {
      if (part?.text) {
        const redacted = await redactSensitiveData(part.text);
        if (redacted !== part.text) {
          part.text = redacted;
          modified = true;
        }
      }
    }
  }

  // Redact sensitive data from system instruction if present
  if (typeof request.systemInstruction === "string") {
    const redacted = await redactSensitiveData(request.systemInstruction);
    if (redacted !== request.systemInstruction) {
      request.systemInstruction = redacted;
      modified = true;
    }
  } else if (request.systemInstruction) {
    const parts = request.systemInstruction.parts ?? [request.systemInstruction];
    for (const part of parts) {
      if (part?.text) {
        const redacted = await redactSensitiveData(part.text);
        if (redacted !== part.text) {
          part.text = redacted;
          modified = true;
        }
      }
    }
  }

  // Returning nothing (or undefined) leaves the request untouched.
  // If modified, return the updated request object.
  if (modified) {
    logger.info("Redacted sensitive data from prompt request");
    return request;
  }
});
// [END ai_logic_before_generate_content]
// [END ai_logic_pre_request]

// [START ai_logic_after_generate_content]
/**
 * Post-request trigger for Firebase AI Logic.
 * Runs after the model generates a response and before it is returned to the client.
 * Inspects all response candidates and redacts any sensitive data generated by the model.
 */
export const redactResponse = afterGenerateContent(async (event) => {
  const response = event.data?.response;
  if (!response?.candidates) return;

  let modified = false;

  // Redact sensitive data from model response candidates
  for (const candidate of response.candidates) {
    for (const part of candidate?.content?.parts ?? []) {
      if (part?.text) {
        const redacted = await redactSensitiveData(part.text);
        if (redacted !== part.text) {
          part.text = redacted;
          modified = true;
        }
      }
    }
  }

  // Returning nothing (or undefined) leaves the response untouched.
  // If modified, return the updated response object.
  if (modified) {
    logger.info("Redacted sensitive data from model response candidates");
    return response;
  }
});
// [END ai_logic_after_generate_content]
// [END ai_logic_sensitive_data_all]

/**
 * Allows injecting a custom DlpServiceClient for testing purposes.
 * @internal
 */
export function setDlpClientForTesting(client) {
  dlp = client;
}
