packages:
  - 2nd-gen/alerts-to-discord/functions
  - 2nd-gen/auth-blocking-functions/functions
  - 2nd-gen/callable-functions/functions
  - 2nd-gen/custom-events/functions
  - 2nd-gen/delete-unused-accounts-cron/functions
  - 2nd-gen/instrument-with-opentelemetry/functions
  - 2nd-gen/monitor-cloud-logging/functions
  - 2nd-gen/pubsub-helloworld/functions
  - 2nd-gen/remote-config-diff/functions
  - 2nd-gen/taskqueues-backup-images/functions
  - 2nd-gen/test-complete/functions
  - 2nd-gen/test-functions-jest/functions
  - 2nd-gen/test-functions-jest-ts/functions
  - 2nd-gen/test-functions-mocha/functions
  - 2nd-gen/testlab-to-slack/functions
  - 2nd-gen/thumbnails/functions
  - 2nd-gen/time-server/functions
  - 2nd-gen/uppercase/functions
  - 2nd-gen/uppercase-firestore/functions
  - assistant-say-number/functions
  - authenticated-json-api/functions
  - authorized-https-endpoint/functions
  - bigquery-import/functions
  - child-count/functions
  - convert-images/functions
  - coupon-on-purchase/functions
  - delete-unused-accounts-cron/functions
  - developer-motivator/functions
  - email-confirmation/functions
  - es2017-transpile/functions
  - exif-images/functions
  - fcm-notifications/functions
  - ffmpeg-convert-audio/functions
  - fulltext-search-firestore/functions
  - fulltext-search/functions
  - github-to-slack/functions
  - google-sheet-sync/functions
  - image-maker/functions
  - image-sharp/functions
  - instagram-auth/functions
  - lastmodified-tracking/functions
  - limit-children/functions
  - linkedin-auth/functions
  - message-translation/functions
  - minimal-webhook/functions
  - moderate-images/functions
  - paypal/functions
  - presence-firestore/functions
  - quickstarts/big-ben/functions
  - quickstarts/email-users/functions
  - quickstarts/pubsub-helloworld/functions
  - quickstarts/runtime-options/functions
  - quickstarts/taskqueues-backup-images/functions
  - quickstarts/thumbnails/functions
  - quickstarts/time-server/functions
  - quickstarts/uppercase-firestore/functions
  - quickstarts/uppercase/functions
  - spotify-auth/functions
  - stripe/functions
  - survey-app-update/functions
  - template-handlebars/functions
  - testlab-to-slack/functions
  - text-moderation/functions
  - url-shortener/functions
  - username-password-auth/functions
  - youtube/functions
