packages:
  - assistant-say-number/functions
  - authenticated-json-api/functions
  - authorized-https-endpoint/functions
  - bigquery-import/functions
  - child-count/functions
  - convert-images/functions
  - coupon-on-purchase/functions
  - delete-unused-accounts-cron/functions
  - developer-motivator/functions
  - email-confirmation/functions
  - es2017-transpile/functions
  - exif-images/functions
  - fcm-notifications/functions
  - ffmpeg-convert-audio/functions
  - fulltext-search-firestore/functions
  - fulltext-search/functions
  - generate-thumbnail/functions
  - github-to-slack/functions
  - google-sheet-sync/functions
  - image-maker/functions
  - image-sharp/functions
  - instagram-auth/functions
  - lastmodified-tracking/functions
  - limit-children/functions
  - linkedin-auth/functions
  - message-translation/functions
  - minimal-webhook/functions
  - moderate-images/functions
  - paypal/functions
  - presence-firestore/functions
  - quickstarts/big-ben/functions
  - quickstarts/email-users/functions
  - quickstarts/pubsub-helloworld/functions
  - quickstarts/runtime-options/functions
  - quickstarts/thumbnails/functions
  - quickstarts/time-server/functions
  - quickstarts/uppercase-firestore/functions
  - quickstarts/uppercase/functions
  - spotify-auth/functions
  - stripe/functions
  - survey-app-update/functions
  - template-handlebars/functions
  - text-moderation/functions
  - url-shortener/functions
  - username-password-auth/functions
  - youtube/functions
