name: multi_counter_server
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  firebase_admin_sdk: ^0.5.0
  firebase_functions: ^0.5.0
  google_cloud_firestore: ^0.5.0
  multi_counter_shared: any # workspace

dev_dependencies:
  build_runner: ^2.4.0
  http: ^1.2.2
