name: https_increment_number
description: HTTPS trigger examples showcasing state increment operations.
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  firebase_functions:
    git:
      url: https://github.com/firebase/firebase-functions-dart
      ref: main
  dart_firebase_admin:
    git:
      url: https://github.com/firebase/firebase-admin-dart
      path: packages/dart_firebase_admin
      ref: main
  google_cloud_firestore:
    git:
      url: https://github.com/firebase/firebase-admin-dart
      path: packages/google_cloud_firestore
      ref: main

dev_dependencies:
  build_runner: ^2.10.5
  lints: ^6.0.0

dependency_overrides:
  dart_firebase_admin:
      git:
        url: https://github.com/firebase/firebase-admin-dart
        path: packages/dart_firebase_admin
        ref: main
  google_cloud_firestore:
      git:
        url: https://github.com/firebase/firebase-admin-dart
        path: packages/google_cloud_firestore
        ref: main
