.TH DVIPDF 1 "26 September 2016" 9.20 Ghostscript \" -*- nroff -*-
.SH NAME
dvipdf \- Convert TeX DVI file to PDF using ghostscript and dvips
.SH SYNOPSIS
\fBdvipdf\fR [ \fIoptions\fR ] \fIinput.dvi\fR [ \fIoutput.pdf\fR ] ...
.SH DESCRIPTION
This script invokes
.BR dvips (1)
with the
.B -q
option, and pipes its output into
.BR gs (1)
with the following options:

.ce
.B -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite

as well as 
.B -sOutputFile
and any options from the command-line.
.SH SEE ALSO
gs(1), dvips(1)
.SH VERSION
This document was last revised for Ghostscript version 9.20.
.SH AUTHOR
Artifex Software, Inc. are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
