.TH GSND 1 "26 September 2016" 9.20 Ghostscript \" -*- nroff -*-
.SH NAME
gsnd \- Run ghostscript (PostScript and PDF engine) without display
.SH SYNOPSIS
\fBgsnd\fR [ \fIoptions\fR ] [ \fIfiles\fR ] ...
.SH DESCRIPTION
This script simply invokes
.BR gs (1)
with the
.B -NODISPLAY
flag, followed by any other arguments from the command-line.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 9.20.
.SH AUTHOR
Artifex Software, Inc. are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
