.TH PFBTOPFA 1 "26 September 2016" 9.20 Ghostscript \" -*- nroff -*-
.SH NAME
pfbtopfa \- Convert Postscript .pfb fonts to .pfa format using ghostscript
.SH SYNOPSIS
\fBpfbtopfa\fR \fIinput.pfb\fR \fI[output.pfa]\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a .pfb file into a .pfa file.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 9.20.
.SH AUTHOR
Artifex Software, Inc. are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
