.TH PS2ASCII 1 "26 September 2016" 9.20 "Ghostscript Tools" \" -*- nroff -*-
.SH NAME
ps2ascii \- Ghostscript translator from PostScript or PDF to ASCII
.SH SYNOPSIS
\fBps2ascii\fR [ \fIinput.ps\fR [ \fIoutput.txt\fR ] ]
.br
\fBps2ascii\fR \fIinput.pdf\fR [ \fIoutput.txt\fR ]
.SH DESCRIPTION
\fBps2ascii\fR uses \fBgs\fR(1) to extract ASCII text from
\fBPostScript\fR(tm) or Adobe \fBPortable Document Format\fR (PDF)
files. If no files are specified on the command line, \fBgs\fR reads from
standard input; but PDF input must come from an explicitly-named file, not
standard input.  If no output file is specified, the ASCII text is written
to standard output.
.PP
\fBps2ascii\fR doesn't look at font encoding, and isn't very good at
dealing with kerning, so for PostScript (but not currently PDF), you might
consider \fBpstotext\fR (see below).
.SH FILES
Run "\fBgs -h\fR" to find the location of Ghostscript documentation on your
system, from which you can get more details.
.SH SEE ALSO
pstotext(1), http://www.research.digital.com/SRC/virtualpaper/pstotext.html
.SH VERSION
This document was last revised for Ghostscript version 9.20.
.SH AUTHOR
Artifex Software, Inc. are the
primary maintainers of Ghostscript.
David M. Jones <dmjones@theory.lcs.mit.edu> made substantial improvements
to \fBps2ascii\fR.
