.TH WFTOPFA 1 "26 September 2016" 9.20 Ghostscript \" -*- nroff -*-
.SH NAME
wftopfa \- Convert a Wadalab base font to Postscript .PFA (or .PFB)
format using ghostscript
.SH SYNOPSIS
\fBwftopfa\fR \fIfontname\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a Wadalab base font to Postscript .PFA (or .PFB)
format.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 9.20.
.SH AUTHOR
Artifex Software, Inc. are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
