.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de> and Thomas Hoffmann
.TH GSND 1 "8.Juli 2002" 7.21 Ghostscript \" -*- nroff -*-
.SH NAME
gsnd \- startet Ghostscript (PostScript- und PDF-Engine) ohne Display
.SH SYNTAX
\fBgsnd\fR [ \fIOptionen\fR ] [ \fIDateien\fR ] ...
.SH BESCHREIBUNG
Das Skript ruft einfach
.BR gs (1)
mit der Option
.B -NODISPLAY
auf, gefolgt von allen anderen Argumenten der Kommandozeile.
.SH SIEHE AUCH
gs(1)
.SH VERSION
Dieses Dokument wurde zuletzt für Ghostscript Version 7.21 durchgesehen.
.SH AUTHOR
Artifex Software, Inc. sind die
Hauptautoren von Ghostscript.
Diese Manpage ist von George Ferguson.
