.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de> and Thomas Hoffmann
.TH PRINTAFM 1 "8.Juli 2002" 7.21 Ghostscript \" -*- nroff -*-
.SH NAME
printafm \- Gibt die Metrik einer Postscript-Schrift im AFM-Format mittels ghostscript aus
.SH SYNTAX
\fBprintafm\fR \fISchriftname\fR
.SH BESCHREIBUNG
Dieses Skript ruft
.BR gs (1)
auf, um die Metrik einer Schrift im AFM-Format zur Standardausgabe (stdout) zu schreiben.
.SH SIEHE AUCH
gs(1)
.SH VERSION
Das Dokument wurde zuletzt für Ghostscript Version 7.21 durchgesehen.
.SH AUTOR
Artifex Software, Inc. sind die
Hauptautoren von Ghostscript.
Diese Manpage ist von George Ferguson.

