.\" Using encoding of the German (de_DE) translation: ISO-8859-1
.\" Translation by Tobias Burnus <burnus@gmx.de> and Thomas Hoffmann
.TH WFTOPFA 1 "8.Juli 2002" 7.21 Ghostscript \" -*- nroff -*-
.SH NAME
wftopfa \- konvertiert eine Wadalab basierte Schrift ins Postscript .PFA- (oder .PFB-)Format mittels Ghostscript.
.SH SYNTAX
\fBwftopfa\fR \fISchriftname\fR
.SH BESCHREIBUNG
Das Skript ruft
.BR gs (1)
auf, um eine Wadalab basierte Schrift in das Postscript .PFA- (oder .PFB-)Format zu konvertiern.
.SH SIEHE AUCH
gs(1)
.SH VERSION
Das Dokument wurde zuletzt für Ghostscript Version 7.21 durchgesehen.
.SH AUTOR
Artifex Software, Inc. sind die
Hauptautoren von Ghostscript.
Diese Manpage ist von George Ferguson.
