# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LINELoginDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LINELoginDemo
  pod 'Firebase/Auth', '3.11.0'
  pod 'GTMHTTPFetcher', '2.0.0'
end
