# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Tests

on:
  pull_request:
    paths:
      - 'Dart/**'

  push:
    branches:
      - main
    paths:
      - 'Dart/**'

env:
  CI: true

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart-version:
          - "3.11.4"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart ${{ matrix.dart-version }}
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: ${{ matrix.dart-version }}

      - name: HTTPS Time Server - Install dependencies
        working-directory: ./Dart/quickstarts/https-time-server
        run: dart pub get

      - name: HTTPS Time Server - Format
        working-directory: ./Dart/quickstarts/https-time-server
        run: dart format --set-exit-if-changed .

      - name: HTTPS Time Server - Analyze
        working-directory: ./Dart/quickstarts/https-time-server
        run: dart analyze .
