name: functions
description: A starting point for Dart Cloud Functions
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  firebase_admin_sdk: ^0.5.6
  firebase_functions: ^0.8.0
  google_cloud_firestore: ^0.5.5
  shared:
    path: ../packages/shared

dev_dependencies:
  lints: ^6.1.0
